// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iştakip.Data;

#nullable disable

namespace iştakip.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240904113248_mig")]
    partial class mig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("iştakip.Models.Birim", b =>
                {
                    b.Property<int>("BirimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BirimId"), 1L, 1);

                    b.Property<string>("BirimAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BirimId");

                    b.ToTable("Birims");
                });

            modelBuilder.Entity("iştakip.Models.Durum", b =>
                {
                    b.Property<int>("DurumId1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DurumId1"), 1L, 1);

                    b.Property<string>("DurumAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DurumId1");

                    b.ToTable("Durums");
                });

            modelBuilder.Entity("iştakip.Models.Is", b =>
                {
                    b.Property<int>("IsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IsId"), 1L, 1);

                    b.Property<DateTime?>("BaslangicTarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DurumId1")
                        .HasColumnType("int");

                    b.Property<string>("IsAcıklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsBaslık")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsDurumId")
                        .HasColumnType("int");

                    b.Property<int?>("IsPersonelId")
                        .HasColumnType("int");

                    b.Property<string>("PersonelBirimId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("int");

                    b.HasKey("IsId");

                    b.HasIndex("DurumId1");

                    b.HasIndex("PersonelId");

                    b.ToTable("Iss");
                });

            modelBuilder.Entity("iştakip.Models.Personel", b =>
                {
                    b.Property<int>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelId"), 1L, 1);

                    b.Property<int?>("BirimId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelAdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelBirimId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelKullanıcıAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonelYetkiTurId")
                        .HasColumnType("int");

                    b.Property<int?>("YetkiTurId")
                        .HasColumnType("int");

                    b.HasKey("PersonelId");

                    b.HasIndex("BirimId");

                    b.HasIndex("YetkiTurId");

                    b.ToTable("Personels");
                });

            modelBuilder.Entity("iştakip.Models.YetkiTur", b =>
                {
                    b.Property<int>("YetkiTurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YetkiTurId"), 1L, 1);

                    b.Property<string>("YetkiTurAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YetkiTurId");

                    b.ToTable("YetkiTurs");
                });

            modelBuilder.Entity("iştakip.Models.Is", b =>
                {
                    b.HasOne("iştakip.Models.Durum", "Durum")
                        .WithMany("Iss")
                        .HasForeignKey("DurumId1");

                    b.HasOne("iştakip.Models.Personel", "Personel")
                        .WithMany("Iss")
                        .HasForeignKey("PersonelId");

                    b.Navigation("Durum");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("iştakip.Models.Personel", b =>
                {
                    b.HasOne("iştakip.Models.Birim", "Birim")
                        .WithMany("Personels")
                        .HasForeignKey("BirimId");

                    b.HasOne("iştakip.Models.YetkiTur", "YetkiTur")
                        .WithMany("Personels")
                        .HasForeignKey("YetkiTurId");

                    b.Navigation("Birim");

                    b.Navigation("YetkiTur");
                });

            modelBuilder.Entity("iştakip.Models.Birim", b =>
                {
                    b.Navigation("Personels");
                });

            modelBuilder.Entity("iştakip.Models.Durum", b =>
                {
                    b.Navigation("Iss");
                });

            modelBuilder.Entity("iştakip.Models.Personel", b =>
                {
                    b.Navigation("Iss");
                });

            modelBuilder.Entity("iştakip.Models.YetkiTur", b =>
                {
                    b.Navigation("Personels");
                });
#pragma warning restore 612, 618
        }
    }
}
